"""
This type stub file was generated by pyright.
"""

html_template = ...
def save_ipyvolumejs(target=..., devmode=..., version=..., version3js=...): # -> str:
    """ output the ipyvolume javascript to a local file
    
    :type target: str
    :type devmode: bool
    :param devmode: if True get index.js from js/dist directory
    :type version: str
    :param version: version number of ipyvolume
    :type version3js: str
    :param version3js: version number of threejs

    """
    ...

def save_requirejs(target=..., version=...): # -> str:
    """ download and save the require javascript to a local file

    :type target: str
    :type version: str
    """
    ...

def save_embed_js(target=..., version=...): # -> str:
    """ download and save the ipywidgets embedding javascript to a local file

    :type target: str
    :type version: str

    """
    ...

def save_font_awesome(dirpath=..., version=...): # -> str:
    """ download and save the font-awesome package to a local directory

    :type dirpath: str
    :type url: str

    """
    ...

def embed_html(filepath, widgets, makedirs=..., title=..., all_states=..., offline=..., scripts_path=..., drop_defaults=..., template=..., template_options=..., devmode=..., offline_cors=...): # -> None:
    """ Write a minimal HTML file with widget views embedded.

    :type filepath: str
    :param filepath: The file to write the HTML output to.
    :type widgets: widget or collection of widgets or None
    :param widgets:The widgets to include views for. If None, all DOMWidgets are included (not just the displayed ones).
    :param makedirs: whether to make directories in the filename path, if they do not already exist
    :param title: title for the html page
    :param all_states: if True, the state of all widgets know to the widget manager is included, else only those in widgets
    :param offline: if True, use local urls for required js/css packages and download all js/css required packages
    (if not already available), such that the html can be viewed with no internet connection
    :param scripts_path: the directory to save required js/css packages to (relative to the filepath)
    :type drop_defaults: bool
    :param drop_defaults: Whether to drop default values from the widget states
    :param template: template string for the html, must contain at least {title} and {snippet} place holders
    :param template_options: list or dict of additional template options
    :param devmode: if True, attempt to get index.js from local js/dist directory
    :param devmode: if True, attempt to get index.js from local js/dist folder
    :param offline_cors: if True, sets crossorigin attribute to anonymous, this allows for the return of error data
    from js scripts but can block local loading of the scripts in some browsers

    """
    ...

