"""
This type stub file was generated by pyright.
"""

"""Some examples for quick testing/demonstrations

All function accept `show` and `draw` arguments

  * If `draw` is `True` it will return the widgets (Scatter, Volume, Mesh)
  * If `draw` is `False`, it will return the data
  * if `show` is `False`, `ipv.show()` will not be called.
"""
def xyz(shape=..., limits=..., spherical=..., sparse=..., centers=...): # -> tuple[NDArray[Any] | Any, NDArray[Any] | Any, NDArray[Any] | Any, Unknown, NDArray[Any], Any] | tuple[NDArray[Any] | Any, NDArray[Any] | Any, NDArray[Any] | Any]:
    ...

def example_ylm(m=..., n=..., shape=..., limits=..., draw=..., show=..., **kwargs): # -> Volume | Any:
    """Show a spherical harmonic"""
    ...

def ball(rmax=..., rmin=..., shape=..., limits=..., draw=..., show=..., **kwargs): # -> Volume:
    """Show a ball"""
    ...

def klein_bottle(draw=..., show=..., figure8=..., endpoint=..., uv=..., wireframe=..., texture=..., both=..., interval=...): # -> Mesh | tuple[list[Unknown] | Any | Unknown, list[Unknown] | Any | Unknown, list[Unknown] | Any, Unknown, Unknown]:
    """Show one or two Klein bottles"""
    ...

def brain(draw=..., show=..., fiducial=..., flat=..., inflated=..., subject=..., interval=..., uv=..., color=...): # -> Mesh | tuple[list[Unknown], list[Unknown], list[Unknown], Unknown]:
    """Show a human brain model

    Requirement:

        $ pip install https://github.com/gallantlab/pycortex
    """
    ...

def head(draw=..., show=..., max_shape=...): # -> Volume:
    """Show a volumetric rendering of a human male head"""
    ...

def gaussian(N=..., draw=..., show=..., seed=..., color=..., marker=...): # -> Scatter | tuple[Any, Any, Any]:
    """Show N random gaussian distributed points using a scatter plot"""
    ...

