"""
This type stub file was generated by pyright.
"""

class MovieMaker:
    def __init__(self, stream, camera, positions=..., quaternions=..., times=..., filename_camera=..., filename_movie=..., overwrite_video=...) -> None:
        ...
    
    def sync_camera(self): # -> None:
        ...
    
    def write_movie(self): # -> None:
        ...
    
    def add(self): # -> None:
        ...
    
    def replace(self): # -> None:
        ...
    
    def remove(self): # -> None:
        ...
    
    def save(self, filename=...): # -> None:
        ...
    
    def load(self, filename=...): # -> None:
        ...
    
    def format_keyframe(self, time, p, q): # -> str:
        ...
    
    def update_keyframes(self): # -> None:
        ...
    
    def show(self): # -> None:
        ...
    


