"""
This type stub file was generated by pyright.
"""

"""
Possible properies

 * background-color
 * axes
  * color
  * visible
  * label
    * color
  * ticklabel
    * color
  * x/y/z
    * color
    * visible
    * label
      * color
    * ticklabel
      * color

Run:
python -m ipyvolume.style
to update the json style (needed for the js side)
"""
styles = ...
_defaults = ...
def create(name, properties):
    ...

light = ...
default = ...
dark = ...
demo = ...
minimal = ...
nobox = ...
if __name__ == "__main__":
    source = ...
    dest = ...
    need_update = ...
