"""
This type stub file was generated by pyright.
"""

from traitlets import TraitType

class Image(TraitType):
    """A trait for PIL images."""
    default_value = ...
    info_text = ...
    def validate(self, obj, value): # -> Image:
        ...
    


